[general]
import = [
  "~/.config/alacritty/themes/ayu_dark.toml",
]

[env]

[window]

[scrolling]
history    = 100000
multiplier = 2

[font]
size = 12.0

[colors]

[bell]
duration = 100

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = false

[keyboard]
bindings = [
  { key = "E", mods = "Alt", action = "ScrollLineDown" },
  { key = "Y", mods = "Alt", action = "ScrollLineUp" },
  { key = "D", mods = "Alt", action = "ScrollHalfPageDown" },
  { key = "U", mods = "Alt", action = "ScrollHalfPageUp" },
  { key = "G", mods = "Alt", action = "ScrollToTop" },
  { key = "G", mods = "Alt|Shift", action = "ScrollToBottom" },
  { key = "X", mods = "Alt|Shift", action = "ToggleViMode" },
  { key = "F", mods = "Alt|Control", action = "SearchForward" },
]

[debug]
# render_timer     = true
# highlight_damage = true
