[general]
live_config_reload = true
ipc_socket         = true

[window]
opacity       = 1.0
dynamic_title = true

[scrolling]
history    = 100000
multiplier = 1

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
size   = 13.0

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = false

[keyboard]
bindings = [
  { key = "E", mods = "Alt", action = "ScrollLineDown" },
  { key = "Y", mods = "Alt", action = "ScrollLineUp" },
  { key = "D", mods = "Alt", action = "ScrollHalfPageDown" },
  { key = "U", mods = "Alt", action = "ScrollHalfPageUp" },
  { key = "G", mods = "Alt", action = "ScrollToTop" },
  { key = "G", mods = "Alt|Shift", action = "ScrollToBottom" },
  { key = "X", mods = "Control|Shift", action = "ToggleViMode" },
  { key = "S", mods = "Control", action = "SearchForward" },
  { key = "S", mods = "Control|Shift", action = "SearchBackward" },
]

[debug]
# render_timer     = true
# highlight_damage = true
