[formatting]
align_entries         = true
array_auto_collapse   = false
array_auto_expand     = false
column_width          = 200
align_comments        = true
allowed_blank_lines   = 1
indent_string         = "  "
trailing_newline      = true
align_single_comments = true
array_trailing_comma  = true
indent_tables         = true
indent_entries        = false
reorder_keys          = false
compact_inline_tables = false
inline_table_expand   = false
