# Unix group containing the Nix build user accounts
build-users-group = nixbld

# Allow unprivileged users to select the TUNA binary cache.
trusted-substituters = https://mirrors.tuna.tsinghua.edu.cn/nix-channels/store
