# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
# "$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
keymap = [
    { on = ["c", "m"], run = "plugin chmod", desc = "Chmod on selected files" },
    { on = "q", run = "escape", desc = "Exit visual mode, clear selected, or cancel search" },
    { on = "<Esc>", run = "quit", desc = "Quit the process" },
    { on = "<C-o>", run = "quit", desc = "Quit the process" },
    { on = "Q", run = "quit --no-cwd-file", desc = "Quit the process without writing cwd-file" },
    { on = "<C-c>", run = "close", desc = "Close the current tab, or quit if it is last tab" },
    { on = "<C-z>", run = "suspend", desc = "Suspend the process" },

    # Hopping
    { on = "k", run = "arrow -1", desc = "Move cursor up" },
    { on = "j", run = "arrow 1", desc = "Move cursor down" },

    { on = "K", run = "arrow -5", desc = "Move cursor up 5 lines" },
    { on = "J", run = "arrow 5", desc = "Move cursor down 5 lines" },

    { on = "<C-u>", run = "arrow -33%", desc = "Move cursor up half page" },
    { on = "<C-d>", run = "arrow 33%", desc = "Move cursor down half page" },
    { on = "<C-b>", run = "arrow -100%", desc = "Move cursor up one page" },
    { on = "<C-f>", run = "arrow 100%", desc = "Move cursor down one page" },

    { on = "h", run = "leave", desc = "Go back to the parent directory" },
    { on = "l", run = "enter", desc = "Enter the child directory" },

    { on = "<C-o>", run = "back", desc = "Go back to the previous directory" },
    { on = "<C-i>", run = "forward", desc = "Go forward to the next directory" },

    { on = "<A-k>", run = "seek -5", desc = "Seek up 5 units in the preview" },
    { on = "<A-j>", run = "seek 5", desc = "Seek down 5 units in the preview" },
    { on = "<Up>", run = "arrow -1", desc = "Move cursor up" },
    { on = "<Down>", run = "arrow 1", desc = "Move cursor down" },
    { on = "<Left>", run = "leave", desc = "Go back to the parent directory" },
    { on = "<Right>", run = "enter", desc = "Enter the child directory" },
    { on = ["g", "g"], run = "arrow top", desc = "Move cursor to the top" },
    { on = "G", run = "arrow bot", desc = "Move cursor to the bottom" },
    { on = "H", run = "back", desc = "Go back to the previous directory" },
    { on = "L", run = "forward", desc = "Go forward to the next directory" },

    # Toggle
    { on = "<Space>", run = ["toggle", "arrow 1"], desc = "Toggle the current selection state" },
    { on = "<C-a>", run = "toggle_all", desc = "Select all files" },
    # { on = "<C-r>", run = "toggle_all on", desc = "Inverse selection of all files" },

    # Visual

    { on = "v", run = "visual_mode", desc = "Enter visual mode (selection mode)" },
    { on = "V", run = "visual_mode --unset", desc = "Enter visual mode (unset mode)" },

    # Spotting
    { on = "<Tab>", run = "spot", desc = "Spot hovered file" },

    # Operation
    { on = "O", run = "open", desc = "Open selected files" },
    { on = "o", run = "open --interactive", desc = "Open  selected files interactively" },
    { on = "e", run = "shell 'xdg-open .'", desc = "Look up in file manager" },
    { on = "<S-e>", run = """shell 'dragon-drop -x -i -T "$1"' """, desc = "Drag and drop" },
    { on = "<Enter>", run = "open", desc = "Open selected files" },
    { on = "<S-Enter>", run = "open --interactive", desc = "Open selected files interactively" },
    { on = ["y", "y"], run = ["escape --visual", "yank"], desc = "Copy selected files" },
    { on = "Y", run = "unyank", desc = "Cancel yank status of files" },
    { on = ["y", "p"], run = ["escape --visual", "copy path"], desc = "Copy absolute path" },
    { on = ["y", "d"], run = ["escape --visual", "copy dirname"], desc = "Copy path of parent directory" },
    { on = ["y", "f"], run = ["escape --visual", "copy filename"], desc = "Copy name of file" },
    { on = ["y", "n"], run = ["escape --visual", "copy name_without_ext"], desc = "Copy name of file without extension" },
    { on = ["y", "c"], run = ["escape --visual", """
        shell '
        if [[ -f $1 ]]; then
            xs < $1
        fi' """], desc = "Copy file content" },
    { on = "x", run = "yank --cut", desc = "Cut selected files" },
    { on = "X", run = "unyank", desc = "Cancel the yank status of files" },
    { on = ["p", "p"], run = "paste", desc = "Paste the files" },
    { on = "P", run = "paste --force", desc = "Paste the files (overwrite if the destination exists)" },
    { on = ["p", "l"], run = "link", desc = "Symlink the absolute path of files" },
    { on = ["p", "L"], run = "link --relative", desc = "Symlink the relative path of files" },
    { on = ["p", "H"], run = "hardlink", desc = "Hardlink yanked files" },
    { on = "d", run = "remove", desc = "Move the files to the trash" },
    { on = "D", run = "remove --permanently", desc = "Permanently delete the files" },
    { on = "a", run = "create", desc = "Create a file or directory (ends with / for directories)" },
    { on = "A", run = "create --dir", desc = "Create a directory" },
    { on = "r", run = "rename --cursor=before_ext", desc = "Rename a file or directory" },
    { on = ";", run = "shell --interactive", desc = "Run a shell command" },
    { on = ":", run = "shell --block --interactive", desc = "Run a shell command (block the UI until the command finishes)" },
    { on = ".", run = "hidden toggle", desc = "Toggle the visibility of hidden files" },
    { on = "s", run = "search fd", desc = "Search files by name using fd" },
    { on = "S", run = "search rg", desc = "Search files by content using ripgrep" },
    { on = "<C-c>", run = "search none", desc = "Cancel the ongoing search" },
    { on = "z", run = "plugin zoxide", desc = "Jump to a directory using zoxide" },
    { on = "Z", run = "plugin fzf", desc = "Jump to a directory, or reveal a file using fzf" },
    { on = "<C-s>", run = '''shell "$SHELL" --block''', desc = "Open shell here" },

    # Linemode
    { on = ["m", "s"], run = "linemode size", desc = "Linemode: size" },
    { on = ["m", "p"], run = "linemode permissions", desc = "Linemode: permissions" },
    { on = ["m", "b"], run = "linemode btime", desc = "Linemode: btime" },
    { on = ["m", "m"], run = "linemode mtime", desc = "Linemode: mtime" },
    { on = ["m", "o"], run = "linemode owner", desc = "Linemode: owner" },
    { on = ["m", "n"], run = "linemode none", desc = "Linemode: none" },

    # Find
    { on = "/", run = "find --smart", desc = "Find next file" },
    { on = "?", run = "find --previous --smart", desc = "Find previous file" },
    { on = "n", run = "find_arrow", desc = "Goto next found file" },
    { on = "N", run = "find_arrow --previous", desc = "Goto previous found file" },

    # Filter
    { on = "f", run = "filter --smart", desc = "Jump to char" },

    # Sorting
    { on = [",", "m"], run = ["sort mtime --reverse=no", "linemode mtime"], desc = "Sort by modified time" },
    { on = [",", "M"], run = ["sort mtime --reverse", "linemode mtime"], desc = "Sort by modified time (reverse)" },
    { on = [",", "b"], run = ["sort btime --reverse=no", "linemode btime"], desc = "Sort by birth time" },
    { on = [",", "B"], run = ["sort btime --reverse", "linemode btime"], desc = "Sort by birth time (reverse)" },
    { on = [",", "e"], run = "sort extension --reverse=no", desc = "Sort by extension" },
    { on = [",", "E"], run = "sort extension --reverse", desc = "Sort by extension (reverse)" },
    { on = [",", "a"], run = "sort alphabetical --reverse=no", desc = "Sort alphabetically" },
    { on = [",", "A"], run = "sort alphabetical --reverse", desc = "Sort alphabetically (reverse)" },
    { on = [",", "n"], run = "sort natural --reverse=no", desc = "Sort naturally" },
    { on = [",", "N"], run = "sort natural --reverse", desc = "Sort naturally (reverse)" },
    { on = [",", "s"], run = ["sort size --reverse=no", "linemode size"], desc = "Sort by size" },
    { on = [",", "S"], run = ["sort size --reverse", "linemode size"], desc = "Sort by size (reverse)" },
    { on = [",", "r"], run = "sort random --reverse=no", desc = "Sort randomly" },

    # Tabs
    { on = "t", run = "tab_create --current", desc = "Create a new tab using the current path" },

    { on = "1", run = "tab_switch 0", desc = "Switch to the first tab" },
    { on = "2", run = "tab_switch 1", desc = "Switch to the second tab" },
    { on = "3", run = "tab_switch 2", desc = "Switch to the third tab" },
    { on = "4", run = "tab_switch 3", desc = "Switch to the fourth tab" },
    { on = "5", run = "tab_switch 4", desc = "Switch to the fifth tab" },
    { on = "6", run = "tab_switch 5", desc = "Switch to the sixth tab" },
    { on = "7", run = "tab_switch 6", desc = "Switch to the seventh tab" },
    { on = "8", run = "tab_switch 7", desc = "Switch to the eighth tab" },
    { on = "9", run = "tab_switch 8", desc = "Switch to the ninth tab" },

    { on = "[", run = "tab_switch -1 --relative", desc = "Switch to the previous tab" },
    { on = "]", run = "tab_switch 1 --relative", desc = "Switch to the next tab" },

    { on = "{", run = "tab_swap -1", desc = "Swap the current tab with the previous tab" },
    { on = "}", run = "tab_swap 1", desc = "Swap the current tab with the next tab" },

    # Tasks
    { on = "w", run = "tasks_show", desc = "Show the tasks manager" },

    # Goto
    { on = ["g", "h"], run = "cd ~", desc = "Goto ~" },
    { on = ["g", "c"], run = "cd ~/.config", desc = "Goto ~/.config" },
    { on = ["g", "d"], run = "cd ~/Downloads", desc = "Goto ~/Downloads" },
    { on = ["g", "t"], run = "cd /tmp", desc = "Goto /tmp" },
    { on = ["g", "u"], run = "cd /run/media", desc = "Goto /run/media" },
    { on = ["g", "v"], run = "cd ~/Videos", desc = "Goto ~/Videos" },
    { on = ["g", "p"], run = "cd ~/Pictures", desc = "Goto ~/Pictures" },
    { on = ["g", "<Space>"], run = "cd --interactive", desc = "Jump interactively" },

    # Help
    { on = "~", run = "help", desc = "Open help" },

    # Plugin
    # { on = "U", run = "plugin searchjump --args='autocd'", desc = "Search Jump(auto cd selected folder)" },
    { on = "U", run = "plugin searchjump", desc = "Search Jump" },
    { on = "F", run = "plugin smart-filter", desc = "Smart filter" },
    { on = "M", run = "plugin max-preview", desc = "Maximize or restore preview" },
    { on = "H", run = "plugin hide-preview", desc = "Hide or show preview" },
    { on = ["R", "p", "p"], run = "plugin sudo -- paste", desc = "sudo paste" },
    { on = ["R", "P"], run = "plugin sudo -- paste --force", desc = "sudo paste --force" },
    { on = ["R", "p", "l"], run = "plugin sudo -- link", desc = "sudo link" },
    { on = ["R", "p", "L"], run = "plugin sudo -- link --relative", desc = "sudo link --relative" },
    { on = ["R", "a"], run = "plugin sudo -- create", desc = "sudo create" },
    { on = ["R", "d"], run = "plugin sudo -- remove", desc = "sudo trash" },
    { on = ["R", "D"], run = "plugin sudo -- remove --permanently", desc = "sudo delete" },
    { on = ["R", "r"], run = "plugin sudo -- rename", desc = "sudo rename" },
]

prepend_keymap = [
    { on = "<C-d>", run = "plugin diff", desc = "Diff the selected with the hovered file" },
    { on = [
        "c",
        "s",
    ], run = "plugin what-size", desc = "Calc size of selection or cwd" },
    { on = [
        "y",
        "s",
    ], run = "plugin clipboard" },
]

[tasks]
keymap = [
    { on = "<Esc>", run = "close", desc = "Hide the task manager" },
    { on = "<C-c>", run = "close", desc = "Hide the task manager" },
    { on = "q", run = "close", desc = "Hide the task manager" },
    { on = "w", run = "close", desc = "Hide the task manager" },
    { on = "k", run = "arrow -1", desc = "Move cursor up" },
    { on = "j", run = "arrow 1", desc = "Move cursor down" },
    { on = "<Up>", run = "arrow -1", desc = "Move cursor up" },
    { on = "<Down>", run = "arrow 1", desc = "Move cursor down" },
    { on = "<Enter>", run = "inspect", desc = "Inspect the task" },
    { on = "x", run = "cancel", desc = "Cancel the task" },
    { on = "~", run = "help", desc = "Open help" },
]

[pick]
keymap = [
    { on = "q", run = "close", desc = "Cancel pick" },
    { on = "<C-c>", run = "close", desc = "Cancel pick" },
    { on = "<Esc>", run = "close", desc = "Cancel pick" },
    { on = "<Enter>", run = "close --submit", desc = "Submit the pick" },

    { on = "k", run = "arrow -1", desc = "Move cursor up" },
    { on = "j", run = "arrow 1", desc = "Move cursor down" },

    { on = "K", run = "arrow -5", desc = "Move cursor up 5 lines" },
    { on = "J", run = "arrow 5", desc = "Move cursor down 5 lines" },

    { on = "<Up>", run = "arrow -1", desc = "Move cursor up" },
    { on = "<Down>", run = "arrow 1", desc = "Move cursor down" },

    { on = "~", run = "help", desc = "Open help" },
    { on = "<F1>", run = "help", desc = "Open help" },
]

[input]
keymap = [
    { on = "<C-c>", run = "close", desc = "Cancel input" },
    { on = "<Esc>", run = "escape", desc = "Go back to normal mode, or cancel input" },
    { on = "<Enter>", run = "close --submit", desc = "Submit the input" },

    # Mode
    { on = "i", run = "insert", desc = "Enter insert mode" },
    { on = "a", run = "insert --append", desc = "Enter append mode" },
    { on = "I", run = ["move -999", "insert"], desc = "Move to the BOL, and enter insert mode" },
    { on = "A", run = ["move 999", "insert --append"], desc = "Move to the EOL, and enter append mode" },
    { on = "v", run = "visual", desc = "Enter visual mode" },
    { on = "V", run = ["move -999", "visual", "move 999"], desc = "Enter visual mode and select all" },

    # Character-wise movement
    { on = "h", run = "move -1", desc = "Move back a character" },
    { on = "l", run = "move 1", desc = "Move forward a character" },
    { on = "<Left>", run = "move -1", desc = "Move back a character" },
    { on = "<Right>", run = "move 1", desc = "Move forward a character" },
    { on = "<C-b>", run = "move -1", desc = "Move back a character" },
    { on = "<C-f>", run = "move 1", desc = "Move forward a character" },

    # Word-wise movement
    { on = "b", run = "backward", desc = "Move back to the start of the current or previous word" },
    { on = "w", run = "forward", desc = "Move forward to the start of the next word" },
    { on = "e", run = "forward --end-of-word", desc = "Move forward to the end of the current or next word" },
    { on = "<A-b>", run = "backward", desc = "Move back to the start of the current or previous word" },
    { on = "<A-f>", run = "forward --end-of-word", desc = "Move forward to the end of the current or next word" },

    # Line-wise movement
    { on = "0", run = "move -999", desc = "Move to the BOL" },
    { on = "$", run = "move 999", desc = "Move to the EOL" },
    { on = "<C-a>", run = "move -999", desc = "Move to the BOL" },
    { on = "<C-e>", run = "move 999", desc = "Move to the EOL" },

    # Delete
    { on = "<Backspace>", run = "backspace", desc = "Delete the character before the cursor" },
    { on = "<C-h>", run = "backspace", desc = "Delete the character before the cursor" },
    { on = "<C-d>", run = "backspace --under", desc = "Delete the character under the cursor" },

    # Kill
    { on = "<C-u>", run = "kill bol", desc = "Kill backwards to the BOL" },
    { on = "<C-k>", run = "kill eol", desc = "Kill forwards to the EOL" },
    { on = "<C-w>", run = "kill backward", desc = "Kill backwards to the start of the current word" },
    { on = "<A-d>", run = "kill forward", desc = "Kill forwards to the end of the current word" },

    # Cut/Yank/Paste
    { on = "d", run = "delete --cut", desc = "Cut the selected characters" },
    { on = "D", run = ["delete --cut", "move 999"], desc = "Cut until the EOL" },
    { on = "c", run = "delete --cut --insert", desc = "Cut the selected characters, and enter insert mode" },
    { on = "C", run = ["delete --cut --insert", "move 999"], desc = "Cut until the EOL, and enter insert mode" },
    { on = "x", run = ["delete --cut", "move 1 --in-operating"], desc = "Cut the current character" },
    { on = "y", run = "yank", desc = "Copy the selected characters" },
    { on = "p", run = "paste", desc = "Paste the copied characters after the cursor" },
    { on = "P", run = "paste --before", desc = "Paste the copied characters before the cursor" },

    # Undo/Redo
    { on = "u", run = "undo", desc = "Undo the last operation" },
    { on = "<C-r>", run = "redo", desc = "Redo the last operation" },

    # Help
    { on = "~", run = "help", desc = "Open help" },
]

[confirm]
keymap = [
    { on = "<Esc>", run = "close", desc = "Cancel the confirm" },
    { on = "<C-[>", run = "close", desc = "Cancel the confirm" },
    { on = "<C-c>", run = "close", desc = "Cancel the confirm" },
    { on = "<Enter>", run = "close --submit", desc = "Submit the confirm" },
    { on = "n", run = "close", desc = "Cancel the confirm" },
    { on = "y", run = "close --submit", desc = "Submit the confirm" },
    { on = "k", run = "arrow -1", desc = "Move cursor up" },
    { on = "j", run = "arrow 1", desc = "Move cursor down" },
    { on = "<Up>", run = "arrow -1", desc = "Move cursor up" },
    { on = "<Down>", run = "arrow 1", desc = "Move cursor down" },
    # Help
    { on = "~", run = "help", desc = "Open help" },
    { on = "<F1>", run = "help", desc = "Open help" },
]

[completion]
keymap = [
    { on = "<C-c>", run = "close", desc = "Cancel completion" },
    { on = "<Tab>", run = "close --submit", desc = "Submit the completion" },
    { on = "<Enter>", run = [
        "close --submit",
        "close_input --submit",
    ], desc = "Submit the completion and input" },
    { on = "<A-k>", run = "arrow -1", desc = "Move cursor up" },
    { on = "<A-j>", run = "arrow 1", desc = "Move cursor down" },
    { on = "<Up>", run = "arrow -1", desc = "Move cursor up" },
    { on = "<Down>", run = "arrow 1", desc = "Move cursor down" },
    { on = "<C-p>", run = "arrow -1", desc = "Move cursor up" },
    { on = "<C-n>", run = "arrow 1", desc = "Move cursor down" },
    { on = "~", run = "help", desc = "Open help" },
]

[help]
keymap = [
    { on = "<Esc>", run = "escape", desc = "Clear the filter, or hide the help" },
    { on = "q", run = "close", desc = "Exit the process" },
    { on = "<C-c>", run = "close", desc = "Hide the help" },

    # Navigation
    { on = "k", run = "arrow -1", desc = "Move cursor up" },
    { on = "j", run = "arrow 1", desc = "Move cursor down" },

    { on = "K", run = "arrow -5", desc = "Move cursor up 5 lines" },
    { on = "J", run = "arrow 5", desc = "Move cursor down 5 lines" },

    { on = "<Up>", run = "arrow -1", desc = "Move cursor up" },
    { on = "<Down>", run = "arrow 1", desc = "Move cursor down" },

    { on = "<S-Up>", run = "arrow -5", desc = "Move cursor up 5 lines" },
    { on = "<S-Down>", run = "arrow 5", desc = "Move cursor down 5 lines" },

    # Filtering
    { on = "/", run = "filter", desc = "Apply a filter for the help items" },
]
