gui:
  sidePanelWidth: 0.4
  # expandFocusedSidePanel: true
  language: en
  # showNumstatInFilesView: true
  commitAuthorShortLength: 2
  border: single
  spinner:
    frames:
      - "⠋"
      - "⠙"
      - "⠹"
      - "⠸"
      - "⠼"
      - "⠴"
      - "⠦"
      - "⠧"
      - "⠇"
      - "⠏"
    rate: 50
git:
  overrideGpg: true
os:
  shellFunctionsFile: ~/.config/zsh/.zshrc
