gui:
  spinner:
    frames:
      - "⠋"
      - "⠙"
      - "⠹"
      - "⠸"
      - "⠼"
      - "⠴"
      - "⠦"
      - "⠧"
      - "⠇"
      - "⠏"
    rate: 50
git:
  overrideGpg: true
os:
  shellFunctionsFile: ~/.config/zsh/.zshrc
