---
# yaml-language-server: $schema=https://raw.githubusercontent.com/mfontanini/presenterm/master/config-file-schema.json
defaults:
  theme: terminal-light
  image_protocol: iterm2

snippet:
  exec:
    enable: true
  render:
    threads: 4
