# Hydrogen

spacing         = 1
padding         = 0
separator       = " "
key_color       = "Yellow"

[custom_ascii]
color = "#00BFFF"
path = "~/.config/macchina/ascii/archlinux.ascii"

[palette]
type = "Full"
visible = false

[bar]
glyph = "o"
symbol_open = '['
symbol_close = ']'
visible = false

[box]
border          = "round"
visible         = true

[box.inner_margin]
x               = 1
y               = 0

[randomize]
key_color       = false
separator_color = false

[keys]
host            = "Host"
kernel          = "Kernel"
os              = "OS"
machine         = "Machine"
de              = "DE"
wm              = "WM"
distro          = "Distro"
terminal        = "Terminal"
shell           = "Shell"
packages        = "Packages"
uptime          = "Uptime"
local_ip        = "Local IP"
memory          = "Memory"
battery         = "Battery"
backlight       = "Brightness"
resolution      = "Resolution"
cpu             = "CPU"
cpu_load        = "CPU Load"
gpu             = "GPU"
disk_space      = "Disk Space"
