# frame = "none"
idle  = false
tabs  = false
vsync = true

[font]
normal = [
    # "InconsolataGo Nerd Font",
    # "RecMonoSmCasual Nerd Font",
    "JetBrainsMono Nerd Font",
    "FiraCode Nerd Font",
    "Noto Sans CJK SC",
]
size = 20
