# frame = "none"
idle  = false
tabs  = false
vsync = true

[font]
normal = [
    "JetBrains Mono",
    "FiraCode Nerd Font",
    "Noto Sans CJK SC",
    "Noto Serif Grantha",
    "Noto Sans Gujarati UI",
]
size = 18
