includes = []
packages = [
  "zsh",
  "bash",
  "fish",
  "nushell",
  "vim",
  "scripts",
  "git",
  "media",
  "terminal",
  "templates",
  "PL",
  "monitor",
  "wayland",
  "gtk",
  "fcitx5",
  # "X",
]
